---

- name: Ensure Python is installed
  raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
  when: ansible_python_version is undefined

-- include_tasks: miniconda.yml
